Allrespondents
platform-for-testing/front pull request #10
Opened 2017-10-03 11:33 UTC by vnormatov

renamed AllRespondentsComponent and added layout for AllRespondentsComponent

2017-10-03 11:45 UTC, tatsiak requested changes
не хватает сущности респондента.
Нужно сверстать, одного респондента и подставлять в него данные с конфига.

2017-10-03 11:45 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.html
> +  <!--<div class="wrapper">-->
это точно лишнее

2017-10-03 11:45 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.html
> +    <div class="Rectangle-5">
нейминг

2017-10-03 11:45 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.html
> +  <div class="wrapper">
для врапера стоит сделать отдельный компонент и в нем добавить возможность брать данные респондентов для отображения.
По аналогии с тестами. 
Далее когда будет готова АПИ - сможем подключить это все друг к другу.

2017-10-03 11:56 UTC, vnormatov commented on src/app/pages/all-respondents/all-respondents.component.html
> +  <div class="wrapper">
это не тот враппер, это для верхней полоски стиль

2017-10-03 11:59 UTC, vnormatov commented on src/app/pages/all-respondents/all-respondents.component.html
> +  <!--<div class="wrapper">-->
убрал

2017-10-03 11:59 UTC, vnormatov commented on src/app/pages/all-respondents/all-respondents.component.html
> +    <div class="Rectangle-5">
fixed

2017-10-03 12:04 UTC, vnormatov commented
респондент будет добавлен позже, как новый компонент

2017-10-03 12:49 UTC, tatsiak reviewed
Оставил комменты.
Мне кажется что, стоит мерджить когда убдет готов компонент и сущность респондента.

2017-10-03 12:49 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.html
> +  <div class="wrapper">
а, ок

2017-10-03 12:49 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.html
> +    <div class="menu">
так как хедер будет универсальным - здесь его можно удалить

2017-10-03 12:49 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.html
> +</div>
не уверен, но мне кажется что какие-то стили применены не верно.
у меня страница отображается вот так http://prntscr.com/gsppj7

2017-10-03 12:49 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.html
> +    <div class="Line-4"></div>
этому классу нужен стиль border-bottom или border-top тогда это будет полоса. Сейчас div отображается как треугольник

2017-10-03 12:49 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.scss
> +.Group-2 {
нейминг

2017-10-03 12:49 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.scss
> +.Rectangle-6 {
нужно удалить стили которые не используются.

2017-10-03 12:49 UTC, tatsiak commented on DrafLayout/normatov/Preview/style2.scss
> +.photo {
это изменено случайно, скоррее всего

2017-10-03 13:06 UTC, vnormatov commented on src/app/pages/all-respondents/all-respondents.component.html
> +    <div class="menu">
не везде он есть и  там где он есть он не одинаковый. Поэтому пока так

2017-10-03 13:09 UTC, vnormatov commented on src/app/pages/all-respondents/all-respondents.component.html
> +    <div class="Line-4"></div>
какой треугольник?)))  У меня все четко) class="Line-4" содержит нужные стили

2017-10-03 13:15 UTC, tatsiak commented
Отпечатался. Отображается как прямоугольник. Я в одном из комментариев
оставлял скриншот - там видно.

On Oct 3, 2017 4:09 PM, "vnormatov" <notifications@github.com> wrote:

> *@vnormatov* commented on this pull request.
> ------------------------------
>
> In src/app/pages/all-respondents/all-respondents.component.html
> <https://github.com/platform-for-testing/front/pull/10#discussion_r142394993>
> :
>
> > +      <i class="fa fa-angle-down"></i>
> +    </div>
> +  </div>
> +  <div class="tetsTitle">
> +    <div class="title-left">
> +      <div class="title-for-list">All Respondents (2)</div>
> +    </div>
> +    <div class="title-right">
> +      <div class="close-menu">All Respondents</div>
> +      <div class="angle-down-respondents">
> +        <i class="fa fa-angle-down"></i>
> +      </div>
> +    </div>
> +  </div>
> +  <div class="wrapper">
> +    <div class="Line-4"></div>
>
> какой треугольник?))) У меня все четко) class="Line-4" содержит нужные
> стили
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/platform-for-testing/front/pull/10#discussion_r142394993>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQ7XumSoMgyxcK9eHgz7XfFMLQrcgHTjks5sojH6gaJpZM4Pr-EZ>
> .
>

2017-10-03 13:15 UTC, vnormatov commented on src/app/pages/all-respondents/all-respondents.component.html
> +</div>
как на макете

2017-10-03 13:16 UTC, vnormatov commented on src/app/pages/all-respondents/all-respondents.component.html
> +    <div class="Line-4"></div>
из макета стиль .Line-4 {
  width: 999px;
  height: 2px;
  border: solid 2px rgba(255, 255, 255, 0.41);
}

2017-10-03 13:18 UTC, tatsiak commented
То что есть в Zeppelin автоматически сгенерировано и почти всегда не
правильно.
Там можно брать цвета, шрифты, какое-то определенные размеры. Если брать
стили пачкой - 100% не будет того что изображенона макете.

On Oct 3, 2017 4:17 PM, "vnormatov" <notifications@github.com> wrote:

> *@vnormatov* commented on this pull request.
> ------------------------------
>
> In src/app/pages/all-respondents/all-respondents.component.html
> <https://github.com/platform-for-testing/front/pull/10#discussion_r142396899>
> :
>
> > +      <i class="fa fa-angle-down"></i>
> +    </div>
> +  </div>
> +  <div class="tetsTitle">
> +    <div class="title-left">
> +      <div class="title-for-list">All Respondents (2)</div>
> +    </div>
> +    <div class="title-right">
> +      <div class="close-menu">All Respondents</div>
> +      <div class="angle-down-respondents">
> +        <i class="fa fa-angle-down"></i>
> +      </div>
> +    </div>
> +  </div>
> +  <div class="wrapper">
> +    <div class="Line-4"></div>
>
> из макета стиль .Line-4 {
> width: 999px;
> height: 2px;
> border: solid 2px rgba(255, 255, 255, 0.41);
> }
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/platform-for-testing/front/pull/10#discussion_r142396899>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQ7Xui-RhT5M9cCN3YgV-kSaOwA4zoM0ks5sojPKgaJpZM4Pr-EZ>
> .
>

2017-10-03 13:25 UTC, vnormatov commented
наша цель, как я понимаю, сделать рабочий функционал, параллельно верстая, а не сделать версту 100% как на макете.

2017-10-03 19:11 UTC, vnormatov commented
По поводу того, что стоить мержить когда будет готов респондет, - не согласен. На начальном этапе, когда ничего нет мержы должны быть маленькими и частыми. В противном случае  погрязнешь в резолве конфликтов. Когда будет готова основа проекта, тогда мерж должен быть при реализованной полностью задачи, но не сейчас.

2017-10-03 19:14 UTC, tatsiak commented
ок, как скажешь

2017-10-03 19:15 UTC, tatsiak submitted a review, later dismissed

2017-10-04 05:11 UTC, YuriiHoliuk requested changes
згоден з тим, що можна мерджити без респондента, хедер пропоную поки що закоментити, а там побачимо

2017-10-04 05:11 UTC, YuriiHoliuk commented on DrafLayout/normatov/Preview/style2.scss
>    width: $width;
ця висота тут вже зайва

2017-10-04 05:11 UTC, YuriiHoliuk commented on src/app/pages/all-respondents/all-respondents.component.html
> +    <div class="test-item">
це треба винести в окремий компонент, можна в наступному PR, якщо тут була мета зробити загальну структуру сторінки

2017-10-04 05:11 UTC, YuriiHoliuk commented on src/app/pages/all-respondents/all-respondents.component.html
> +  <div class="header-content">
думаю хедер варто спробувати зробити глобальним, якщо вже не вийде, тоді будемо дублювати

2017-10-04 06:19 UTC, vnormatov commented on DrafLayout/normatov/Preview/style2.scss
>    width: $width;
эти правки тут случайные. Это старый шаблон, он не актуальный

2017-10-04 06:20 UTC, vnormatov commented on src/app/pages/all-respondents/all-respondents.component.html
> +  <div class="header-content">
удалиить его можна всегда. Будет глобальный  -  грохнем)

2017-10-04 06:20 UTC, vnormatov commented on src/app/pages/all-respondents/all-respondents.component.html
> +    <div class="test-item">
планировал в след реквесте эту реализацию.

2017-10-04 06:25 UTC, vnormatov commented on DrafLayout/normatov/Preview/style2.scss
> +.photo {
+

2017-10-04 08:10 UTC, vnormatov commented
Добавил компонент респондента и подключил общий header

2017-10-04 08:43 UTC, tatsiak commented
конфликты

2017-10-04 08:49 UTC, tatsiak requested changes

2017-10-04 08:49 UTC, tatsiak commented on src/app/pages/all-respondents/all-respondents.component.html
> +<pt-header></pt-header>
Необходимо вмерджить девелоп.
После мерджа и резолва конфликтов не нужно будет подключать хедер.

2017-10-04 09:23 UTC, tatsiak commented
вмерджил девелоп в ветку, зарезолвил конфликты, убрал хедер из компонента страницы

2017-10-04 09:23 UTC, tatsiak submitted a review, later dismissed

2017-10-04 10:11 UTC, yuchiko approved these changes
png хорошо заменить потом на svg, и оставить только fallback для старых девайсов

2017-10-04 10:16 UTC, tatsiak approved these changes
approve

2017-10-04 18:53 UTC, YuriiHoliuk approved these changes

2017-10-04 18:53 UTC, merged