Add download image component, this task not finished
platform-for-testing/front pull request #14
Opened 2017-10-07 07:49 UTC by VjacheslavMorozov

Сделал загрузчик изображения, кнопки нет, работает не совсем корректно

2017-10-07 19:03 UTC, YuriiHoliuk requested changes

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.html
> +<label class="uploader" ondragover="return false;" [class.loaded]="loaded" [style.outlineColor]="dragging ? activeColor : baseColor" (dragenter)="handleDragEnter()" (dragleave)="handleDragLeave()" (d
- ondragover це звичайний inline js, а не angular, думаю краще так не писати
- замість style думаю краще використати class тут ж нічого не вираховується просто switch між двома кольорами
- опціонально, можна тоді використати ngClass
- такі довгі строки краще переносити на кілька ліній, важко читати
- і питання. такі стандартні івенти існують на всіх елементах?

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.html
> +        ? ((imageSrc.length > 0) ? overlayColor : activeColor)
як на мене забагато логіки в темплейті, краще винести в js

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.scss
> +    background-color: #efefef;
про змінні сьогодні говорили

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
>    selector: 'pt-app-create-new-test-uploader',
а для чого префікс app, якщо в нас є pt, треба повидаляти, я бачив і в інших компонентах

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +export class CreateNewTestUploaderComponent {
а чому не просто image uploader? якась занадто специфічна назва

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +    imageSrc: String = 'https://upload.wikimedia.org/wikipedia/commons/c/cd/View_from_connors_hill_panorama.jpg';
всюди де я бачив типи записані lowercase, не бачу сенсу писати з великої і думаю тут буде трохи інше значення, як в js об'єкт Number

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +    borderColor: String = 'transparent';
ці кольори може користувач настроювати? якщо так то ок, а якщо ні, то думаю їх можна захардкодити в css, бо це ж не компонент в ui-library а для конкретного використання

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +    imageLoaded: Boolean = false;
знов Uppercase, і наш tslint(стандартний ангулярівський) настроєний на те, що колиприсвоюєш примітив тип не потрібно вказувати

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +  inputs:['activeColor','baseColor','overlayColor']
хоч синтаксис @Input() довгий на https://angular.io/guide/styleguide рекомендують використовувати його і пояснюють чому

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +        this.loaded = false;
як на мене isLoading краще відображає суть

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +    _handleReaderLoaded(e) {
для чого underscore? ми домовились ніби в приватних його не ставити, а це взагалі public метод

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +        if (this.imageSrc.length === 0) {
а ці дві перевірки точно мають бути однакові

2017-10-07 19:03 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +    _setActive() {
не бачу де ці функції використовуються

2017-10-07 19:04 UTC, YuriiHoliuk commented
тести завалились

2017-10-08 19:39 UTC, VjacheslavMorozov commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.html
> +<label class="uploader" ondragover="return false;" [class.loaded]="loaded" [style.outlineColor]="dragging ? activeColor : baseColor" (dragenter)="handleDragEnter()" (dragleave)="handleDragLeave()" (d
Про сложные  ивенты - почищу лишнее

2017-10-11 21:20 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-uploader/create-new-test-uploader.component.ts
> +  imageLoaded: boolean = false;
а для чого два флажки loaded і imageLoaded?

2017-10-15 17:08 UTC, closed without merging