All tests tatsiak
platform-for-testing/front pull request #2
Opened 2017-09-28 11:15 UTC by tatsiak

насетапил роутинг
поставил заглушку - свою верстку на страницу all activations 
сделал хедер который подходит для страницы all tests

2017-09-28 14:12 UTC, vnormatov commented
Сережа, я кучу изменений в эту ветку только что внес, после Юриных замечаний. Предлагаю обновиться, что б не было тех же граблей что и у меня

2017-09-28 18:05 UTC, YuriiHoliuk requested changes
Класна сова

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/all-tests.component.html
> +<pt-header></pt-header>
header в app.component є

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-activations/all-activations.component.html
> +      <i class="fa fa-angle-up arrow_activations" style="font-size:24px"></i>
класи в основному пишуть кебаб кейсом, underscore хіба для бем елементів. це навіть по fa-angle-up видно

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-activations/all-activations.component.html
> +    <span class="button_not_active">Ended</span>
а тут просто button

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-activations/all-activations.component.html
> +    <span class="button_active">Active</span>
тут краще 2 класи зробити button active тоді клас active можна додавати/забирати js-ом

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-activations/all-activations.component.html
> +    <span class="rectangles">&#9633;<br>&#9633;<br>&#9633;</span>
тут краще думаю menu-button, щось таке

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-activations/all-activations.component.html
> +    <span class="ends_in_days">End in 9 days</span>
amount_of_participants, ends_in_days можна якось покоротше, але це вже придирки

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/create-new-block/create-new-block.component.html
> +        <span class="text_my_tests">My tests</span>
тут, як і в багатьох місцях, варто привязуватись не до того, що написано в макеті, а якось узагальнювати, тоді і css буде менший виходити

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/create-new-block/create-new-block.component.html
> +        <form action="/create-new-test">
action відправить форму на сервер, а нам треба передати її в js, зробити валідацію, і тоді вирішувати, що з нею робити. Але це окрема тема, тут думаю можна і так залишити

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/create-new-block/create-new-block.component.html
> +            <input type="submit" value="+ Create new" class="create_new"/>
для такого є placeholder, я про value підказку, бо так прийдеться стирати при заповненні

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/create-new-block/create-new-block.component.scss
> +  margin-right: 702px;
мігічні цифри

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/create-new-block/create-new-block.component.scss
> +  margin-bottom: 48px;
а тут магічні цифри більш менш умісні

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/create-new-block/create-new-block.component.scss
> +  background-color: #8be8a3;
кольори, шрифти можна в змінні винести, простіше читати буде

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/header/header.component.scss
> +pt-tools{
до таких штук класи не задаються, якщо дуже треба, то є :host {}. А взагалі компонент має буди інкапсульований, не має афектити інші, тобто без margin, float. А розміщенням компонентів краще керувати в вищому(навіть додаванням додаткових обгорток), тоді компоненти виходять більш реюзабельні

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/header/tools/tools.component.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
ух ти, навіть не знав, що так можна. Але це точно не best practice))

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/header/tools/tools.component.html
> +        <i class="fa fa-angle-down" style="font-size:24px"></i>
інлайн стилі

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/header/tools/tools.component.html
> +    <span class="icon-wrap"><img class="img" [src]="imageGlassPath"></span>
тут гуд, але задавати такі штуки з js варто, якщо вони можуть мінятись/приходять з сервера і т. п.

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/header/tools/tools.component.scss
> +  position: absolute;
position absolute має відносно обмежене застосування, думаю це не той випадок

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-activations/all-activations.component.html
> +    <div class="short_horizontal_line"></div>
краще задавати border до елементів/ ::before/::after якщо лінія коротша чи щось складніше

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/all-tests/header/tools/tools.component.scss
> +.line{
код стайл

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/app/app.module.ts
> +import { TestItemComponent } from './all-tests/wraper/test-item/test-item.component';
тут теж код стайл, пробіли десь є десь немає, я за те щоб були, але головне притримуватись чогось одного

2017-09-28 18:05 UTC, YuriiHoliuk commented on src/index.html
> +<body style="background-color: #c5c7e0; padding: 0">
згрішив

2017-09-29 08:23 UTC, tatsiak commented on src/app/all-activations/all-activations.component.html
> +      <i class="fa fa-angle-up arrow_activations" style="font-size:24px"></i>
в цьому випадку залишу як є, бо це заглушка а не повноцінна верстка сторінки. На майбутнє буду юзати кебаб-кейс

2017-09-29 08:25 UTC, tatsiak commented on src/app/all-tests/all-tests.component.html
> +<pt-header></pt-header>
я бачив, але зараз не знаю як зробити його реюзабельним. В кожній сторінці свій набір кнопок

2017-09-29 08:27 UTC, tatsiak commented on src/app/all-tests/create-new-block/create-new-block.component.html
> +            <input type="submit" value="+ Create new" class="create_new"/>
тут не дуже розумію про що ти. 
Ця форма з інпутом відображається як звичайна конпка. 
З самого початку я робив button але коли не зміг додати до нього href то нагуглив це рішення

2017-10-01 05:15 UTC, tatsiak commented on src/app/all-tests/create-new-block/create-new-block.component.scss
> +  background-color: #8be8a3;
done

2017-10-01 05:41 UTC, tatsiak commented on src/index.html
> +<body style="background-color: #c5c7e0; padding: 0">
fixed

2017-10-01 05:42 UTC, tatsiak commented on src/app/app.module.ts
> +import { TestItemComponent } from './all-tests/wraper/test-item/test-item.component';
це був автоімпорт від пхпшторма
поправив

2017-10-01 05:45 UTC, tatsiak commented on src/app/all-tests/create-new-block/create-new-block.component.html
> +        <span class="text_my_tests">My tests</span>
fixed

2017-10-01 05:46 UTC, tatsiak commented on src/app/all-tests/header/tools/tools.component.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
переніс в глобальний html

2017-10-01 05:48 UTC, tatsiak commented on src/app/all-tests/header/tools/tools.component.scss
> +.line{
fixed

2017-10-01 05:49 UTC, tatsiak commented on src/app/all-tests/header/tools/tools.component.html
> +        <i class="fa fa-angle-down" style="font-size:24px"></i>
виніс в scss

2017-10-01 05:52 UTC, tatsiak commented on src/app/all-tests/header/header.component.scss
> +pt-tools{
fixed

2017-10-01 09:41 UTC, YuriiHoliuk approved these changes

2017-10-01 09:42 UTC, merged