New question
platform-for-testing/front pull request #21
Opened 2017-10-21 21:21 UTC by yrbn

2017-10-27 08:05 UTC, YuriiHoliuk requested changes

2017-10-27 08:05 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-multiselect/create-new-test-multiselect.component.html
> +          (click)="writeValue(mulselItem.label)"
- я розумію, що це і до того було, але думаю 3 лісенери на клік на один елемент малувато, треба додати четвертий
- click - не найкраща назва для функції
- mulsel - теж не сильно описує ситуацію

2017-10-27 08:05 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-multiselect/create-new-test-multiselect.component.ts
> +  styleUrls: ['./create-new-test-multiselect.component.scss'],
взагалі такий компонент мав би бути просто select/multiselect/dropdown і бути реюзабельним, а не спеціально під new question

2017-10-27 08:05 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/create-new-test-multiselect/create-new-test-multiselect.component.ts
> +    this.writeValue = fn;
це неправильно, ти перезаписуєш функцію writeValue, а маєш створювати нову propagateChange, вони виконують різні функції

2017-10-27 08:05 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/question-list/fileuploader/fileuploader.component.scss
> +	box-sizing: border-box;
tab

2017-10-27 08:05 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/question-list/question-list.component.html
> +<form [formGroup]="form"
якось виглядає ніби цей PR має багато спільного з попереднім

2017-10-27 08:05 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/question-list/question-list.component.ts
> +  questions: Question[] = []; yield;
yield?

2017-10-27 10:40 UTC, dzudzylo commented
Юр, дякую за рев'ю. Запушив із фіксами + зробив селект як компонент із ./shared

2017-10-27 18:04 UTC, YuriiHoliuk commented on src/app/pages/create-new-test/question-list/question/question.component.ts
> +  currentType(value) {
взагалі класно, що є такий івент і селект можна використовувати не тільки в формах, а і просто так, але тут по ходу ця функція зайва. І в універсальному селекті такий івент мав би називатись більш загально

2017-10-28 08:28 UTC, YuriiHoliuk approved these changes

2017-10-28 08:29 UTC, merged