Add three dots in header
platform-for-testing/front pull request #32
Opened 2017-11-10 21:20 UTC by tatsiak

2017-11-10 21:27 UTC, yuchiko requested changes

2017-11-10 21:27 UTC, yuchiko commented on src/app/shared/components/header/tools/tools.component.scss
> +	outline: none !important;
`!important` лучше вообще не использовать в твоем коде

2017-11-10 21:27 UTC, yuchiko commented on src/app/shared/components/header/tools/tools.component.scss
> +	outline: none !important;
с оutline аккуратно, когда его отменяешь, таким образом ты сразу бедным людям, которые пользуются интерфейсом с клавиатуры, убираешь возможность пользоваться нашим сервисом комфортно.

2017-11-10 21:27 UTC, yuchiko commented on src/app/shared/components/header/tools/tools.component.scss
> +	border: none;
тут 80% прописанных свойств обьявленны для того, чтобы кнопка перестала быть кнопкой. Лучше такое делать через @extend. Просто создай где-то нужые себе свойства обнуления кнопки %no-btn и наследуй их. Или придумай общий для всех класс `no-btn` чтобы мы его юзали, когда у нас такая ситуация.

2017-11-10 21:27 UTC, yuchiko commented on src/app/shared/components/header/tools/tools.component.html
> +        <button class="three-dots">&#8942;</button>
не забудь, что по-умолчанию тип кнопки submit, лучше в этом случае уточнить, что `type="button"`

2017-11-11 06:27 UTC, tatsiak commented on src/app/shared/components/header/tools/tools.component.scss
> +	outline: none !important;
убрал outline

2017-11-11 06:28 UTC, tatsiak commented on src/app/shared/components/header/tools/tools.component.scss
> +	outline: none !important;
это попало сюда случайно.

2017-11-11 06:29 UTC, tatsiak commented on src/app/shared/components/header/tools/tools.component.scss
> +	border: none;
на самом деле большинство свойств попали сюда случайно. У меня не получалось обнулить стили и я по очереди добавлял разные варианты обнулений. 
Мне нужен только border: none; 
Все остальное удалил.

2017-11-11 12:45 UTC, yuchiko approved these changes

2017-11-11 13:17 UTC, merged